# Q1

In [32]:
import numpy as np
A = np.matrix(np.array([[1,2,1],[1,3,2],[2,5,3],[2,0,1],[3,1,1]]).astype('float64'))
b = np.matrix(np.array([-1,2,0,1,-2]).astype('float64')).T
ATA = A.T*A
ATb = A.T*b
print('A.T*A')
print(ATA)
print('A.T*b')
print(ATb)
augment = np.concatenate([ATA,ATb], axis=1)
print('row reduce')
print(augment)
print('R1 -> (1/19)*R1')
augment[0] = (1/augment[0,0])*augment[0]
print(augment)
print('R2 -> R2 - (18)*R1')
augment[1] = augment[1] - (augment[1,0])*augment[0]
print(augment)
print('R3 -> R3 - (14)*R1')
augment[2] = augment[2] - (augment[2,0])*augment[0]
print(augment)
print('R2 -> (19/417)*R2')
augment[1] = (1/augment[1,1])*augment[1]
print(augment)
print('R3 -> (19/4)*R3')
augment[2] = (19/4)*augment[2]
print(augment)
print('R1 -> R1 - (18/19)*R2')
augment[0] = augment[0] - (augment[0,1])*augment[1]
print(augment)
print('R3 -> R3 - (51)*R2')
augment[2] = augment[2] - (augment[2,1])*augment[1]
print(augment)
print('R3 -> (139/285)*R3')
augment[2] = (1/augment[2,2])*augment[2]
print(augment)
print('R1 -> R1 - (38/139)*R3')
augment[0] = augment[0] - (augment[0,2])*augment[2]
print(augment)
print('R2 -> R2 - (68/139)*R3')
augment[1] = augment[1] - (augment[1,2])*augment[2]
print(augment)

A.T*A
[[19. 18. 14.]
 [18. 39. 24.]
 [14. 24. 16.]]
A.T*b
[[-3.]
 [ 2.]
 [ 2.]]
row reduce
[[19. 18. 14. -3.]
 [18. 39. 24.  2.]
 [14. 24. 16.  2.]]
R1 -> (1/19)*R1
[[ 1.          0.94736842  0.73684211 -0.15789474]
 [18.         39.         24.          2.        ]
 [14.         24.         16.          2.        ]]
R2 -> R2 - (18)*R1
[[ 1.          0.94736842  0.73684211 -0.15789474]
 [ 0.         21.94736842 10.73684211  4.84210526]
 [14.         24.         16.          2.        ]]
R3 -> R3 - (14)*R1
[[ 1.          0.94736842  0.73684211 -0.15789474]
 [ 0.         21.94736842 10.73684211  4.84210526]
 [ 0.         10.73684211  5.68421053  4.21052632]]
R2 -> (19/417)*R2
[[ 1.          0.94736842  0.73684211 -0.15789474]
 [ 0.          1.          0.48920863  0.2206235 ]
 [ 0.         10.73684211  5.68421053  4.21052632]]
R3 -> (19/4)*R3
[[ 1.          0.94736842  0.73684211 -0.15789474]
 [ 0.          1.          0.48920863  0.2206235 ]
 [ 0.         51.         27.         20.    

# Q3
## a)
projection = A(A^T\*A)^(-1)A^T\*b
## b)

In [20]:
A = np.matrix(np.array([[-1,2],[2,-3],[-1,3]]).astype('float64'))
b = np.matrix(np.array([4,1,2]).astype('float64')).T

print(A)
print(b)
print('A.T*A')
print(A.T*A)
print('det(A.T*A)')
print(np.linalg.det(A.T*A))
print('inverse of (A.T*A)')
print((A.T*A).I)
print('compared to answer I got:')
print((1/11)*np.matrix([[22,11],[11,6]]))
print('A.t*b')
print(A.T*b)
print('(A.T*A).I*A.T*b')
print((A.T*A).I*A.T*b)
print('A*(A.T*A).I*A.T*b')
print(A*(A.T*A).I*A.T*b)

[[-1.  2.]
 [ 2. -3.]
 [-1.  3.]]
[[4.]
 [1.]
 [2.]]
A.T*A
[[  6. -11.]
 [-11.  22.]]
det(A.T*A)
11.000000000000002
inverse of (A.T*A)
[[2.         1.        ]
 [1.         0.54545455]]
compared to answer I got:
[[2.         1.        ]
 [1.         0.54545455]]
A.t*b
[[-4.]
 [11.]]
(A.T*A).I*A.T*b
[[3.]
 [2.]]
A*(A.T*A).I*A.T*b
[[1.00000000e+00]
 [1.33226763e-15]
 [3.00000000e+00]]


# Q4
## a)

In [21]:
x = np.array([10,11,12,14,15]).astype('float64')
y = np.array([21.34,20.68,20.05,18.87,18.3]).astype('float64')
A = np.matrix([np.exp(-0.02*x), np.exp(-0.07*x)]).T # We want the rows to be columns, easier for notation
print("A")
print(A)
b = np.matrix(y).T
print('b')
print(b)

A
[[0.81873075 0.4965853 ]
 [0.8025188  0.46301307]
 [0.78662786 0.43171052]
 [0.75578374 0.3753111 ]
 [0.74081822 0.34993775]]
b
[[21.34]
 [20.68]
 [20.05]
 [18.87]
 [18.3 ]]


In [22]:
ATA = A.T*A
print('ATA')
print(ATA)
ATb = A.T*b
print('ATb')
print(ATb)

ATA
[[3.05316056 1.66063616]
 [1.66063616 0.91066689]]
ATb
[[77.65830427]
 [42.31401787]]


Solve A^T\*Ax = A^T\*b

Invert the matrix A^T\*A

In [23]:
det = np.linalg.det(ATA)
print(f'det = {det}')
inverse = (1/det) * np.matrix([[ATA[1,1], -ATA[0,1]], [-ATA[1,0], ATA[0,0]]])
print(inverse)
inverse = ATA.I

det = 0.022699764890928835
[[ 40.11789968 -73.15653583]
 [-73.15653583 134.50185821]]


Solve x = (A^T\*A)^(-1)\*A^T\*b

In [24]:
xhat = inverse * ATb
print(xhat)
print(f'So xhat = ({xhat[0,0]}, {xhat[1,0]})')

[[19.94109495]
 [10.10151413]]
So xhat = (19.941094946093926, 10.101514133434648)


So M_A = 19.941094946093926 & M_B = 10.101514133434648

So the least squares curve is y = 19.941094946093926\*e^(-0.02\*t) + 10.101514133434648\*e^(-0.07\*t)

In [25]:
f = lambda x: xhat[0,0]*np.exp(-0.02*x)+xhat[1,0]*np.exp(-0.07*x)
print('Verifying')
print(', '.join([f'({i}, {f(i)})' for i in x]))

Verifying
(10.0, 21.342651147119877), (11.0, 20.680236599705765), (12.0, 20.047150818742242), (14.0, 18.862365716565026), (15.0, 18.307627594879143)


## b)

In [26]:
print(f(30))

12.180900283599552
