# Q4
## a)

In [1]:
import numpy as np
x = np.array([10,11,12,14,15])
y = np.array([21.34,20.68,20.05,18.87,18.3])
A = np.matrix([np.exp(-0.02*x), np.exp(-0.07*x)]).T # We want the rows to be columns, easier for notation
print("A")
print(A)
b = np.matrix(y).T
print('b')
print(b)

A
[[0.81873075 0.4965853 ]
 [0.8025188  0.46301307]
 [0.78662786 0.43171052]
 [0.75578374 0.3753111 ]
 [0.74081822 0.34993775]]
b
[[21.34]
 [20.68]
 [20.05]
 [18.87]
 [18.3 ]]


In [2]:
ATA = A.T*A
print('ATA')
print(ATA)
ATb = A.T*b
print('ATb')
print(ATb)

ATA
[[3.05316056 1.66063616]
 [1.66063616 0.91066689]]
ATb
[[77.65830427]
 [42.31401787]]


Solve A^T\*Ax = A^T\*b

Augment the matrix

In [3]:
augment = np.concatenate((ATA, ATb), axis=1)
print(augment)

[[ 3.05316056  1.66063616 77.65830427]
 [ 1.66063616  0.91066689 42.31401787]]


Multiply row 1 by 1/3.05316056

In [4]:
augment[0] = (1/augment[0,0]) * augment[0]
print(augment)

[[ 1.          0.54390725 25.43538172]
 [ 1.66063616  0.91066689 42.31401787]]


Subtract 1.66063616 \* Row 1 from row 2

In [5]:
augment[1] = augment[1] - (augment[1,0])*augment[0]
print(augment)

[[1.00000000e+00 5.43907250e-01 2.54353817e+01]
 [0.00000000e+00 7.43484152e-03 7.51031567e-02]]


Multiply row 1 by 1/7.43484152e-03

In [6]:
augment[1] = (1/augment[1,1]) * augment[1]
print(augment)

[[ 1.          0.54390725 25.43538172]
 [ 0.          1.         10.10151413]]


Subtract 0.54390725 \* Row 2 from row 1

In [7]:
augment[0] = augment[0] - (augment[0,1])*augment[1]
print(augment)

[[ 1.          0.         19.94109495]
 [ 0.          1.         10.10151413]]


In [9]:
xhat = np.array((augment[0,2], augment[1,2]))
print(f'xhat = ({xhat[0]}, {xhat[1]})')

xhat = (19.94109494609435, 10.101514133434172)


So M_A = 19.94109494609435 & M_B = 10.101514133434172

So the least squares curve is y = 19.94109494609435\*e^(-0.02\*t) + 10.101514133434172\*e^(-0.07\*t)

In [12]:
f = lambda x: xhat[0]*np.exp(-0.02*x)+xhat[1]*np.exp(-0.07*x)
print('Verifying')
print(', '.join([f'({i}, {f(i)})' for i in x]))

Verifying
(10, 21.34265114711999), (11, 20.680236599705882), (12, 20.04715081874237), (14, 18.86236571656517), (15, 18.30762759487929)


## b)

In [13]:
print(f(30))

12.180900283599726
