# Q4
## a)

In [1]:
import numpy as np
x = np.array([10,11,12,14,15])
y = np.array([21.34,20.68,20.05,18.87,18.3])
A = np.matrix([np.exp(-0.02*x), np.exp(-0.07*x)]).T # We want the rows to be columns, easier for notation
print("A")
print(A)
b = np.matrix(y).T
print('b')
print(b)

A
[[0.81873075 0.4965853 ]
 [0.8025188  0.46301307]
 [0.78662786 0.43171052]
 [0.75578374 0.3753111 ]
 [0.74081822 0.34993775]]
b
[[21.34]
 [20.68]
 [20.05]
 [18.87]
 [18.3 ]]


In [2]:
ATA = A.T*A
print('ATA')
print(ATA)
ATb = A.T*b
print('ATb')
print(ATb)

ATA
[[3.05316056 1.66063616]
 [1.66063616 0.91066689]]
ATb
[[77.65830427]
 [42.31401787]]


Solve A^T\*Ax = A^T\*b

Invert the matrix A^T\*A

In [3]:
det = np.linalg.det(ATA)
print(f'det = {det}')
inverse = (1/det) * np.matrix([[ATA[1,1], -ATA[0,1]], [-ATA[1,0], ATA[0,0]]])
print(inverse)
inverse = ATA.I

det = 0.022699764890928835
[[ 40.11789968 -73.15653583]
 [-73.15653583 134.50185821]]


Solve x = (A^T\*A)^(-1)\*A^T\*b

In [4]:
xhat = inverse * ATb
print(xhat)
print(f'So xhat = ({xhat[0,0]}, {xhat[1,0]})')

[[19.94109495]
 [10.10151413]]
So xhat = (19.941094946093926, 10.101514133434648)


So M_A = 19.941094946093926 & M_B = 10.101514133434648

So the least squares curve is y = 19.941094946093926\*e^(-0.02\*t) + 10.101514133434648\*e^(-0.07\*t)

In [5]:
f = lambda x: xhat[0,0]*np.exp(-0.02*x)+xhat[1,0]*np.exp(-0.07*x)
print('Verifying')
print(', '.join([f'({i}, {f(i)})' for i in x]))

Verifying
(10, 21.342651147119877), (11, 20.680236599705765), (12, 20.047150818742242), (14, 18.862365716565026), (15, 18.307627594879143)


## b)

In [6]:
print(f(30))

12.180900283599552
