# Q3
## A)

In [1]:
import numpy as np

In [2]:
t = np.matrix([  1, 1.1, 1.5, 1.9,   2, 2.2, 2.3, 2.5])
y = np.matrix([1.1, 0.9, 1.6, 2.2, 1.6, 2.9, 2.7, 2.4])
print('t =', t)
print('y =', y)

t = [[1.  1.1 1.5 1.9 2.  2.2 2.3 2.5]]
y = [[1.1 0.9 1.6 2.2 1.6 2.9 2.7 2.4]]


Start by constructing the data matrix.

In [3]:
X = np.concatenate([t, y], axis=0)
print('X =')
print(X)

X =
[[1.  1.1 1.5 1.9 2.  2.2 2.3 2.5]
 [1.1 0.9 1.6 2.2 1.6 2.9 2.7 2.4]]


Put the matrix X in mean-deviation form.
Find the average of each row

In [4]:
mu = np.matrix(np.apply_along_axis(np.average, axis=1, arr=X))
print('mu =')
print(mu.T)

mu =
[[1.8125]
 [1.925 ]]


Subtract mu from each column

In [5]:
X_hat = np.matrix(np.apply_along_axis(func1d=lambda x: x - mu, axis=0, arr=X))
print('X hat = ')
print(X_hat)

X hat = 
[[-0.8125 -0.7125 -0.3125  0.0875  0.1875  0.3875  0.4875  0.6875]
 [-0.825  -1.025  -0.325   0.275  -0.325   0.975   0.775   0.475 ]]


Find the covariance matrix, C = (1/(n-1))\*X_hat\*X_hat^T

Solve A = X_hat*X_hat^T

In [6]:
A = X_hat * X_hat.T
print('A =')
print(A)

A =
[[2.16875 2.5475 ]
 [2.5475  3.795  ]]


Solve C = (1/(n-1))\*A

In [7]:
n = t.shape[-1]
print('n =',n)
C = (1/(n-1))*A
print('C =')
print(C)

n = 8
C =
[[0.30982143 0.36392857]
 [0.36392857 0.54214286]]


Perform SVD on C

In [8]:
U, S, V_t = np.linalg.svd(C)
V = V_t.T
S = np.diag(S)
print('U =')
print(U)
print('S =')
print(S)
print('V =')
print(V)

U =
[[-0.58988483 -0.80748739]
 [-0.80748739  0.58988483]]
S =
[[0.80799957 0.        ]
 [0.         0.04396471]]
V =
[[-0.58988483 -0.80748739]
 [-0.80748739  0.58988483]]


The vector V contains the principal components, explicitly list them

In [9]:
PC1 = V[:,0]
print('first principal component:')
print(PC1)
PC2 = V[:,1]
print('second principal component:')
print(PC2)

first principal component:
[[-0.58988483]
 [-0.80748739]]
second principal component:
[[-0.80748739]
 [ 0.58988483]]


Calculate how much of the total variance corresponds to the first principal component

In [10]:
tot_var = S.trace()
print('total variance:',tot_var)
PC1_dir_amount = S[0,0]/tot_var
print('Percentage in the direction of the first principal component: {:.2f}%'.format(PC1_dir_amount*100))

total variance: 0.8519642857142857
Percentage in the direction of the first principal component: 94.84%
